### PR TITLE
Tag new release

### PR DESCRIPTION
**Pull request by dkanada**

### CODE REVIEW

**Comment by dkanada** [comment]
This is blocked again until we can figure out the image issues.

**Comment by anthonylavado** [comment]
@dkanada Image issues?

**Comment by dkanada** [comment]
@thornbill was concerned that images were taking longer to load and might not even be cached between restarts. The former might be a change by us but I can't think of a reason the latter has shown up lately.

**Comment by dkanada** [comment]
I just tested a local build and the issue doesn't seem to be as problematic as I expected.

**Pull request merged**
