### PR TITLE
Add playback tracking support for mpv-android external player

### LINKED ISSUE #149: No tracking for mpv-android external player
image

MX-player is closed (bad track record on pinging to unknown servers), VLC player has tons of features that are **not needed**/ **BLOAT** for just jellyfin playback. mpv-android is the best foss minimalist player perfect for jellyfin. Do take a look.

https://github.com/mpv-android/mpv-android

### PR DESCRIPTION
**Pull request by CarlosOlivo**
Closes #149

Note: Release of mpv-android with https://github.com/mpv-android/mpv-android/commit/f70298fe23c4872ea04fe4f2a8b378b986460d98 not available yet.

### CODE REVIEW

**Comment by Maxr1998** [comment]
Nice, thanks for taking care of this! Let me know once it's merged and released in mpv so I can review this :+1:

**Comment by CarlosOlivo** [comment]
> Nice, thanks for taking care of this! Let me know once it's merged and released in mpv so I can review this 👍

Well, it's already merged, only the release is missing, sorry in advance, I know that asking for ETA is rude, but @sfan5 do you have plans to make a new build release soon? Either way this can wait, there's no rush.

**Comment by sfan5** [comment]
I assume you don't want to release the support early because it would be confusing to users that the latest version of mpv-android can't actually do playback tracking, is that correct?

**Comment by Maxr1998** [comment]
I think that's the point, yes.

**Comment by sfan5** [comment]
Here you go: https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2020-10-13

**Review by Maxr1998 — APPROVED** [review]

**Comment by CarlosOlivo** [comment]
mpv-android requires the extra "position" to be an integer unlike MX & VLC Android that allows long type, so I change that.

**Review by Maxr1998 — APPROVED** [review]

**Review by nielsvanvelzen — APPROVED** [review]

**Pull request merged**
