### PR TITLE
adding forgotten featureGraphic

### PR DESCRIPTION
**Pull request by IzzySoft**
Oy… forgot one image. Pulled it from your Google listing. If you have the 1024x500 variant, you can replace this (it's either 1024x500 which I could not obtain, or 512x250 which I was able to retrieve; on smartphones, it shouldn't really matter, but on a highres 10" tablet one can probably tell the difference).

### CODE REVIEW

**Comment by Maxr1998** [comment]
We should actually be able to render out an SVG to the preferred size. With that, we can also ensure equal padding at the top and bottom (that's currently not the case). I can look into it if you want, but for reference, we'd take this one as a base: https://github.com/jellyfin/jellyfin-ux/blob/master/branding/SVG/banner-dark.svg

**Comment by IzzySoft** [comment]
That seems to be the one the current featureGraphic is based upon as well. If you want me to retract this PR, feel free to close (no bad feelings) and add the featureGraphic at your own schedule, it's nothing essential. Or you could merge it now, and replace the graphic later – whatever seems best to you.

**Comment by Maxr1998** [comment]
> That seems to be the one the current featureGraphic is based upon as well. If you want me to retract this PR, feel free to close (no bad feelings) and add the featureGraphic at your own schedule, it's nothing essential. Or you could merge it now, and replace the graphic later – whatever seems best to you.

I think I'll fix the graphic tomorrow, but push it to your PR :sweat_smile:
That way, we don't forget about it.

**Review by Maxr1998 — APPROVED** [review]

**Comment by IzzySoft** [comment]
Yay, thanks! Yeah, definitely looks better (correctly centered etc). Replaced it at my end (effective tomorrow with the next sync) and will cleanup my fork now.

**Comment by IzzySoft** [comment]
PS, one short question as it wasn't clear from all the descriptions I've checked: would the Jellyfin server be visible/act-as DLNA server by the "usual DLNA products" (receiver, TV etc)? Because then I'd like to check it out for myself if I find some time…

**Comment by h1dden-da3m0n** [comment]
> PS, one short question as it wasn't clear from all the descriptions I've checked: would the Jellyfin server be visible/act-as DLNA server by the "usual DLNA products" (receiver, TV etc)? Because then I'd like to check it out for myself if I find some time…

It should work with the usual DLNA players, yet there are problems with it at times. It is one of the features that gets a lot of attention on the official Jellyfin Reddit with "Help Requests". In my experience it works fine, but then I only have a limited sample size/use. Thre are big changes coming to it as well as soon as the servers BIG networking rework gets merged (full network backed rework IIRC).

Hope this helps and hope you like it as much as we do, should you try it out ;)

**Comment by IzzySoft** [comment]
Thanks a lot, @h1dden-da3m0n – sounds fair enough to me! I currently use minidlnad (no idea if that does any transcoding at all), so my "DLNA requirements" are as limited as your sample size :rofl: – mostly photos, occasionally MP3s, and now-and-then a movie (mostly my own from vacations). With that in mind, I'll certainly see to give it a try (no ETA though, but that certainly moves it up the ranks)!

**Pull request merged**
