### PR TITLE
Media notification improvements

### PR DESCRIPTION
**Pull request by Maxr1998**
- Supply duration metadata to mediaSession/notification
- Support media seek bar on Android 10 (and earlier custom ROMs that backported this) - however handling click events will require additional changes to jellyfin-web
- Make notification "ongoing" as long as the playback is running
- Show album name instead of when/chronometer progress on N and above (notification subText is shown in header since N)
- Remove unnecessary callback super calls

### CODE REVIEW

**Comment by Maxr1998** [comment]
Regarding the necessary changes for seeking to the web client - I have already implemented those, and will issue a separate PR to that project very soon.

**Comment by rexbron** [comment]
Would the change to ongoing notifications close #305?

**Comment by dkanada** [comment]
The features look good to me, we just have to get the build working and this should be fine. If you'd like to make other improvements we have a huge list of things the Android client needs :laughing: it's a bit of a beast.

**Comment by Maxr1998** [comment]
@rexbron #235 should be closed through this, but unfortunately the first issue still stands - the web client sometimes doesn't properly propagate updates to the notification, especially if the app is in background. This is, however, unrelated to this PR. Might be related to jellyfin/web, or the Cordova bindings, I'm not sure.

**Comment by Maxr1998** [comment]
@dkanada I'm not entirely sure why the build fails, I don't think it's related to my PR.
Obligatory "it built fine on *my* machine", lol.

**Comment by dkanada** [comment]
Hmmmm I don't know who ran it again but it's passing now.

**Comment by Maxr1998** [comment]
Nice! So, should be good to merge now, right?

**Comment by Maxr1998** [comment]
Just rebased onto the latest master, and tested my changes again. Would appreciate if they could be merged in soon :P

**Comment by hamburglar2160** [comment]
I just ran this on Android 11. As you said, the notification seek bar thing is still a problem until a JF-web merge is done. Is there a web PR that you can link here? With this merged, it's still a significant improvement over what's there but we'll have the seekbar issue.

What will it take to get a stop button there to force the notification away? As best I can tell, I need to return to the app and pause/stop from there.

**Comment by Maxr1998** [comment]
> I just ran this on Android 11. As you said, the notification seek bar thing is still a problem until a JF-web merge is done. Is there a web PR that you can link here?

Unfortunately not. I plan to rework my above patches that I attached above once the merge is through, though, and the build issues are fixes. Without a way to test, I don't want to open a PR for that change yet. Still, the seekbar already "works", just the seeking is a no-op that's reverted on the next notification update. So, I think it's not really necessary to have this fixed before merging.

> What will it take to get a stop button there to force the notification away? As best I can tell, I need to return to the app and pause/stop from there.

Good question. Shouldn't normally be too hard, for now, I always force-closed Jellyfin if the notification got stuck. Still, this seems to be a web/Cordova issue, the update callback just isn't called on the notification.

**Comment by hamburglar2160** [comment]
Ah. Well if it's helpful, [here's ](https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=7629&view=artifacts&type=publishedArtifacts)the APK built out with your PR. Choose the debug build and you probably need to uninstall your previous APK.

Regarding my previous second point, one could just pause THEN swipe away the notification. The obvious benefit to having the persistent notification is that swiping it away will not end playback. Ideally though there'd be a "stop" or "X" button to just outright end playback. Here's an example.
image

The other thing I notice is that you can't collapse the notification. It is stuck at "full, open" position. That, to me, is a blocker.

**Comment by dkanada** [comment]
@Maxr1998 we do have a wrapper function to call a native preference screen, so if you want to add preferences like when swipe to close is available or download options let me know. I'm not a fan of the close button, I'd rather have a preference for something like that.

**Comment by Maxr1998** [comment]
@dkanda sorry, was a bit busy and didn't manage to reply. Only being able to dismiss when the playback is paused is the best option imo, and doesn't require any preference. Still, the underlying issue that the notification doesn't get updated with the latest state still needs fixing. Afaik there were plans anyway to move away from Cordova, which might fix that as well.

Anyway, thanks for the merge!

**Comment by dkanada** [comment]
The migration from Cordova is still some time away and hasn't been finalized, so we'll be keeping this code for a while I think. We have a few possible avenues for the move, from native clients that wrap a WebView like this one, or a single codebase shared by Android and Android TV devices.

**Pull request merged**
