### PR TITLE
Add ffmpeg extension to ExoPlayer

### PR DESCRIPTION
**Pull request by maulik9898**
Audio codec supported : Vorbis, Opus, FLAC, ALAC, PCM/WAVE (μ-law, A-law), MP1, MP2, MP3, AMR (NB, WB), AAC (LC, ELD, HE; xHE on Android 9+), **AC-3, E-AC-3, DTS, DTS-HD, TrueHD**
Video codec supported : H.265 HEVC, MPEG-4 SP, VP8, VP9, AV1

### CODE REVIEW

**Comment by Maxr1998** [comment]
Thanks for your contribution! I'm not a fan of have a pre-packaged binary library in the repo, so we'll probably have to change some things. But it's a good start already, will make it easier for me to properly implement it.

**Comment by maulik9898** [comment]
Just a quick question. According to exoplayer [documentation,](https://exoplayer.dev/supported-formats.html#standalone-subtitle-formats) it supports SSA/ASS type subtitles. Then why it is not enabled.

**Comment by nielsvanvelzen** [comment]
ExoPlayer doesn't really support ssa/ass subtitles, it only shows the text from them and ignore syling/animation etc. That's why we do not enable it.

**Comment by Maxr1998** [comment]
Update: we published a pre-built extension on mavenCentral, and integrated it to the app with #520. Thus, this PR can be closed now. Thanks again for the contribution!

I'll cherry-pick the one missing change about the TS packet size later after evaluating it.

**Pull request closed without merging**
