### PR TITLE
Add External player option

### PR DESCRIPTION
**Pull request by grafixeyehero**

### CODE REVIEW

**Comment by thornbill** [comment]
What does enabling this actually do? lol

**Comment by grafixeyehero** [comment]
@thornbill https://github.com/jellyfin/jellyfin-web/blob/a4dabc1644ac3e4f0b242a5760698e658c91fcda/src/components/playbacksettings/playbacksettings.js#L171 but the cordova externalplayer.js not fully implemented

**Comment by grafixeyehero** [comment]
@thornbill https://github.com/jellyfin/jellyfin-web/blob/a4dabc1644ac3e4f0b242a5760698e658c91fcda/src/components/playbacksettings/playbacksettings.js#L171 but the cordova externalplayer.js not fully implemented

**Comment by thornbill** [comment]
Oh I see so this change will enable the feature in web, but we will need additional changes on the Android side to get it working.

**Pull request merged**
