### PR TITLE
Revert "Set appMode for webui"

### LINKED ISSUE #153: Setting appMode to 'android' prevents server connection on fresh installs (rc.7)
**Describe the bug**
I try to enter the server but it does not enter. The three versions of the rc.-7 version (release, unsigned and debug) do not work. When you put the url of the server and click on connect, the app pretends to be entering the server, but then it returns to the same host screen.

**To Reproduce**
1. Enter the url of the server
2. Click on Connect
3. Jellyfin logo
4. Return to the same screen to enter the Host

**System:**
 - App version: [2.0.0-rc.7]
 - Android version: [Android 9
 - Device manufacturer and model: [10.6.4]

### PR DESCRIPTION
**Pull request by Maxr1998**
Reverts #146
Closes #153

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
I think we should actually look into what additional changes we should make to fix #153 instead of removing the appmode, as it does make some changes that are required in the webui.

**Comment by Maxr1998** [comment]
> I think we should actually look into what additional changes we should make to fix #153 instead of removing the appmode, as it does make some changes that are required in the webui.

We could first try whether `appMode='cordova'` works better, yes. But if it's an obscure bug that can't easily be fixed, I wouldn't spend too much time on it..
The cast code has issues regardless of the appMode.

**Comment by nielsvanvelzen** [comment]
Setting the appmode to cordova is the same as android

**Review by nielsvanvelzen — APPROVED** [review]
Let's just revert it for now

**Pull request merged**
