### PR TITLE
Exoplayer implementation

### PR DESCRIPTION
**Pull request by vitorsemeano**
This PR introduces new advancements bringing exoplayer to android client.

In this PR is included basic event propagation, like play, pause, end and playing. Playing given file it will start at the last position that was recorded. 

I would appreciate some help regarding the UI, because i am not experienced with it.

My next improvement would be media support detection. Using the current android api, i should be able to fetch all supported codecs for a current device, and build a more accurate device profile.

### CODE REVIEW

**Comment by Rijul-A** [comment]
I think this could close #169 right? Thank you. I will try.

**Comment by JustAMan** [comment]
@vitorsemeano what still makes this a WIP? I mean, what's still missing?

**Comment by vitorsemeano** [comment]
It's still missing full layout oriented for jellyfin (using default exoplayer view for now), we can't choose reliably subtitles (part because there is no ui yet to choose subtitle tracks as audio tracks).

As discussed previously with @dkanada, a player chooser should be implemented to give the capability to the user to choose what player he wants to use. 

For now, i have been refining containers/codecs support using android apis to fetch this information, converting it to jellyfin device profile, using conditions for profiles and levels.

If tracks selection and a jellyfin look to this player is not a big priority, this PR is functional as it is.

If this get's accepted, one will still need to enable it from code without the player chooser, and compile it.

**Comment by anthonylavado** [comment]
I mean, if it gets it in, and we create two items to track what needs to happen next, I think we should merge.

The two new items:
* add a player chooser
* add the interface to select tracks

**Comment by vitorsemeano** [comment]
I agree with you. This will not break the current players. Until the player chooser is not done, this can be activated using a manual compilation after changing the exoplayer to be used in nativeshell.js.

The interface is minimal, but it works. My suggestion is to extend from the exoplayer views and adapt it to include track selection between other things (poster, movie/episode name, continue next track if activated, etc)

**Pull request merged**
