### PR TITLE
Fix Build Issues

### PR DESCRIPTION
**Pull request by Matt07211**
This fixes:
- Automated Licence agreement
- Missing gradle dependices

### CODE REVIEW

**Comment by joshuaboniface** [comment]
Hah the irony is I had `yes |` before and it *stopped* working.

**Comment by Matt07211** [comment]
You aren't the first to say this, but 7 out of 7 compiles I've tried and it worked every time ¯\_(ツ)_/¯

**Comment by joshuaboniface** [comment]
Are you also able to add this diff in too? It's needed on my side as well otherwise the Docker sometimes fails with NPM errors:

```
diff --git a/build.sh b/build.sh
index a757999e3..63cea3133 100755
--- a/build.sh
+++ b/build.sh
@@ -9,6 +9,7 @@ cd ${SOURCE_DIR}
 export NODE_ENV=production
 #export NODE_ENV=development

+npm i npm@latest -g
 npm cache verify
 npm install
 npx gulp
```

I'm not sure if it's happening to anyone else too, but shouldn't hurt AFAIK.

**Comment by thornbill** [comment]
Also don’t forget to add yourself to CONTTRIBUTORS.md :smile:

**Comment by Matt07211** [comment]
Pushed the requested change

> Also don’t forget to add yourself to CONTRIBUTORS.md
I'll remember to do that if I ever do push more then a couple of changes

**Comment by LeoVerto** [comment]
> Hah the irony is I had `yes |` before and it _stopped_ working.

Maybe we were just always too impatient when testing this :P

**Comment by joshuaboniface** [comment]
@LeoVerto At one point it was over 20mins, but I expect it was doing something (slowly) and just not showing it. I always assumed it was frozen.

**Pull request merged**
