### PR TITLE
Use gulp for building www directory

### PR DESCRIPTION
**Pull request by thornbill**
In preparation of updating the `dashboard-ui`, this moves the contents of `www` to `src`. All the content from `dashboard-ui` moved to `src/dashboard-ui` and the code specific to Cordova moved to `src/cordova`.

`gulp` build tasks were added to handle minifying the source files and copying them to the `www` directory.

I was thinking a `gulp` task could also be used to make the necessary modifications to `dashboard-ui` files instead of the API endpoint on the Jellyfin server.

~Flagging this as WIP since it will need rebased once the changes in #17 are merged.~

### CODE REVIEW

**Comment by joshuaboniface** [comment]
@thornbill I merged #17 can you rebase to clean up those conflicts?

**Comment by thornbill** [comment]
Rebase complete.

**Comment by dkanada** [comment]
Turns out package-lock.json can be useful, thanks for the good read @thornbill =) still not a fan of npm so it's a shame we need to use it for the build. Let me know what you think about the other points.

**Comment by thornbill** [comment]
I think the biggest advantage to moving to something like `gulp` is to reduce the amount of custom logic needed to perform these build tasks. `gulp` also facilitates piping the output of tasks to different places. In this case the Cordova scripts are output to `www/cordova` while the others are output to `www`.

I would also like to migrate the logic from the [PackageCreator](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.WebDashboard/Api/PackageCreator.cs) to a gulp task. This would allow `dashboard-ui` to be updated without needing to run a local build of the Jellyfin server with the input/output paths modified.

Eventually most of this functionality could probably be handled by a build system in a repository for `dashboard-ui` (or whatever it maybe called). This seemed like a good stop-gap solution in the meantime.

Just for future reference, the article @dkanada mentioned about `package-lock.json` is [here](https://medium.com/coinmonks/everything-you-wanted-to-know-about-package-lock-json-b81911aa8ab8)

**Pull request merged**
