### PR TITLE
Allow to exit from fullscreen with the back button in ExoPlayer

### PR DESCRIPTION
**Pull request by timm0e**
When using ExoPlayer, this allows users to exit the full-screen mode by pressing the back button, similar to e.g. the YouTube app.

### CODE REVIEW

**Review by Maxr1998 — APPROVED** [review]
Sounds reasonable. Thanks for the contribution!

**Comment by elnoelsi** [comment]
Im not sure if this was the change but now when i use back gesture it goes to portrait mode from landscape mode instead of actually leaving fullscreen @Maxr1998

**Comment by elnoelsi** [comment]
i dont mean to be offensive, but this is pretty useless behavior forcing you to take 2 actions if you want to close the player, no matter what. its actually horrible cause after leaving landscape you have to move your finger to a different edge to be able to back gesture. 

i dont see how it could ever be useful, if i want to close the player i want to do just that. if i want extra options/info i will tap the screen. its pretty standard behavior on every app and player that ive used. 

at least give an option to disable it or have it disabled when "start landscape mode" is enabled. 

i dont think i can emphasize enough how much of a pain it is to have to gesture back twice every time i need to close the player, it doesnt even pause it. if i wanted to hair on portrait mode i would press "exit full screen" icon that is there for a reason.

**Comment by mdinger** [comment]
Is there an option to disable this?

**Comment by elnoelsi** [comment]
There is no option thats the most annoying part of all, i genuinely think you have to be masochist to enjoy this feature in any way

**Comment by nielsvanvelzen** [comment]
Please open an issue so we can discuss this change. If there is a high demand for a revert/preference we may consider it.

**Comment by mdinger** [comment]
@nielsvanvelzen as suggested, please see #1256

**Pull request merged**
