### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by Maxr1998**
@nielsvanvelzen: after approving, please let me rebase before merging!

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by nielsvanvelzen** [comment]
@Maxr1998 rebase time!

**Comment by Maxr1998** [comment]
> @Maxr1998 rebase time!

Oh no, I just got up xD Now if I could just have GitHub rebase it automatically..

**Comment by nielsvanvelzen** [comment]
I can squash merge 👀

**Comment by Maxr1998** [comment]
> I can squash merge 👀 

Hm, would've been more obvious to what components changed. But since that'll still be in the description, I guess we could do that. So, go ahead ^^

**Pull request merged**
